### ISSUE TITLE
SL: continue train failed to load weight.

### ISSUE THREAD

**Issue by madallion** [MicrosoftGeekHub/AlphaGo#25]

**Comment by madallion** [comment]
cmdline:
call D:\yimlin\RocAlphaGo\r.bat

Error message:
Traceback (most recent call last):
 File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
 "main", fname, loader, pkg_name)
 File "C:\Python27\lib\runpy.py", line 72, in _run_code
 exec code in run_globals
 File "D:\yimlin\RocAlphaGo\AlphaGo\training\supervised_policy_trainer.py", line 216, in <module>
 run_training()
 File "D:\yimlin\RocAlphaGo\AlphaGo\training\supervised_policy_trainer.py", line 125, in run_training
 model.load_weights(os.path.join(args.out_directory, args.weights))
 File "C:\Python27\lib\site-packages\keras\engine\topology.py", line 2286, in load_weights
 str(len(flattened_layers)) + ' layers.')
Exception: You are trying to load a weight file containing 9 layers into a model with 8 layers.
